### ISSUE TITLE
Original Lab README not Reflected in Assessment and Conduct Format Guidelines

### ISSUE THREAD

**Issue by koscinskic** [Allegheny-Computer-Science-203-S2020/cs203-S2020-markdown#4]
After reviewing the original README files provided in both of the lab 1 repositories upon initial assignment, the README expects that "For each skill and its assessment level, you should also clearly explain what a student must do to demonstrate mastery at the level of 😎..." (Quote Continues to provide additional instruction)

Very few team members have adhered to this original requirement, and neither of the guidelines in this repository have addressed this content. There are pull requests being denied due to this discrepancy.

Seeing as this blurb is a critical component of the assignment, this is a request calling for the Markdown team to reassess their format guidelines to more accurately reflect the guidelines provided in the original README.

**Comment by bagashvilit** [comment]
@koscinskic Thank you for raising this issue. Markdown team discussed it during the laboratory session and decided to remove the part where you have to provide an explanation for how to achieve the level of :sunglasses: because we thought that it would be rephrasing what was already mentioned in the bullet points. Please refer to the template and let us know if there are any issues.
